# Generated by Django 3.2.18 on 2023-03-12 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('question_no', models.AutoField(db_column='question no', primary_key=True, serialize=False)),
                ('question', models.CharField(max_length=100)),
                ('option_1', models.CharField(max_length=50)),
                ('option_2', models.CharField(max_length=50)),
                ('option_3', models.CharField(max_length=50)),
                ('option_4', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'questions',
                'managed': False,
            },
        ),
    ]
