# Generated by Django 3.2.18 on 2023-03-12 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Analysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('question_no', models.IntegerField()),
                ('answer', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'analysis',
                'managed': False,
            },
        ),
    ]
