# Generated by Django 3.2.18 on 2023-03-12 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Register',
            fields=[
                ('register_id', models.AutoField(primary_key=True, serialize=False)),
                ('firstname', models.CharField(max_length=20)),
                ('lastname', models.CharField(max_length=20)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(max_length=10)),
                ('email_id', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=11)),
            ],
            options={
                'db_table': 'register',
                'managed': False,
            },
        ),
    ]
