# Generated by Django 3.2.18 on 2023-03-12 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cbot',
            fields=[
                ('cbot_id', models.AutoField(primary_key=True, serialize=False)),
                ('resp', models.CharField(max_length=100)),
                ('quest', models.CharField(max_length=50)),
                ('uid', models.IntegerField()),
            ],
            options={
                'db_table': 'cbot',
                'managed': False,
            },
        ),
    ]
